import {StyleSheet} from 'react-native';

const gaya = StyleSheet.create({
  box: {
    flex: 1,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  title: {
    justifyContent: 'flex-start',
    textAlign: 'center',
    fontSize: 50,
    fontWeight: 'bold',
    color: 'rgba(0, 87, 156, 1)',
    fontFamily: 'Roboto',
  },
  filltext: {
    fontSize: 13,
    fontWeight: 'bold',
    marginTop: 25,
    color: 'black',
  },
  textInput: {
    backgroundColor: 'rgba(239, 244, 244, 1)',
    borderRadius: 10,
    flex: 1,
    marginLeft: 10,
  },
  iconTextInput: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(239, 244, 244, 1)',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginBottom: 5,
  },
  viewAnother: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
  },
  TextCountPenumpang: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    backgroundColor: 'rgba(239, 244, 244, 1)',
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    marginTop: '5%',
  },
  jumlah: {
    color: 'rgba(0, 87, 156, 1)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 330,
    borderWidth: 0.5,
    borderRadius: 5,
    padding: 10,
    height: 40,
    marginVertical: 15,
    borderColor: '#dddddd',
  },
  tanggal: {
    color: 'black',
    fontWeight: '100',
    fontFamily: 'Roboto',
    flexDirection: 'column',
    flex: 1,
    marginLeft: 15,
    justifyContent: 'flex-start',
    fontSize: 17,
  },
  boxKecil: {
    backgroundColor: 'rgba(239, 244, 244, 1)',
    marginTop: 10,
    borderRadius: 10,
    flex: 0,
    width: 337,
    height: 320,
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'border: 1px solid rgba(0, 0, 0, 0.21)',
  },
  viewButtonDetail: {
    margin: 40,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonDetail: {
    backgroundColor: '#0094FF',
    margin: 8,
    padding: 2,
    textAlign: 'center',
    borderRadius: 8,
    color: 'white',
    justifyContent: 'center',
  },
  textButton: {
    textAlign: 'center',
    color: 'white',
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  textButtonDetails: {
    textAlign: 'center',
    color: 'Black',
    fontSize: 17,
    backgroundColor: '#0094FF',
  },
  textButtonDetailsBack: {
    textAlign: 'center',
    color: 'Black',
    fontSize: 17,
    backgroundColor: 'white',
    borderColor: '#0094FF',
  },
  keberangkatanLayout: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  keberangkatan: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -30,
    marginLeft: 20,
    marginRight: 20,
  },
  keberangkatanText: {
    fontSize: 25,
    fontWeight: 'bold',
    color: 'black',
    fontFamily: 'Roboto',
  },
  jadwal: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
    fontFamily: 'Roboto',
  },
  marginJadwal: {
    marginLeft: 20,
    marginTop: -20,
    paddingTop: 40,
  },
  marginLayanan: {
    marginLeft: 20,
    marginTop: 20,
  },
  iconArrow: {
    marginTop: 33,
    fontSize: 30,
    color: 'black',
  },
  line: {
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 12,
  },
  text: {
    fontSize: 17,
    color: 'black',
    fontWeight: '400',
  },
  textHarga: {
    fontSize: 17,
    color: 'black',
    fontWeight: '400',
    paddingTop: 14,
  },
  textDewasa: {
    fontSize: 17,
    color: 'black',
    fontWeight: '400',
    paddingTop: 14,
  },
  textHargaMargin: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 20,
    marginRight: 20,
  },
  identitas: {
    backgroundColor: '#fff',
    borderRadius: 6,
    borderColor: '#dddddd',
    flex: 1,
  },
  block: {
    fontSize: 100,
    color: '#FB461E',
    fontWeight: 'bold',
    alignContent: 'center',
  },
});

export default gaya;
